{{- if .Values.virtualService.enabled }}
{{ $fullName := include "vc-issuer.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
  - "{{ .Values.virtualService.host }}"
  gateways:
  - {{ .Values.virtualService.gateway }}
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ $fullName }}
{{- end }}
