apiVersion: v1
kind: Service
metadata:
  name: {{ include "vc-issuer.fullname" . }}
  labels: {{ include "vc-issuer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: {{ include "vc-issuer.selectorLabels" . | nindent 4 }}
